### ISSUE TITLE
salt.master fails in salt-ssh: TemplateNotFound: salt/formulas.jinja

### ISSUE THREAD

**Issue by ryanfields** [saltstack-formulas/salt-formula#140]
I'm attempting to use salt-ssh 2015.5.0 to set up a salt master.  The salt.master state is failing.

```
----------
          ID: salt-master
    Function: file.recurse
        Name: /etc/salt/master.d
      Result: False
     Comment: #### /etc/salt/master.d/f_defaults.conf ####
              Unable to manage file: Jinja error: salt/formulas.jinja
              Traceback (most recent call last):
                File "/tmp/.root_679d2e__salt/salt/utils/templates.py", line 306, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/tmp/.root_679d2e__salt/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/tmp/.root_679d2e__salt/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 15, in top-level template code
                File "/tmp/.root_679d2e__salt/salt/utils/jinja.py", line 110, in get_source
                  raise TemplateNotFound(template)
              TemplateNotFound: salt/formulas.jinja
              
              ; line 15
              
              ---
              [...]
              {{ configname }}: {{ cfg_salt[configname] }}
              {%- else -%}
              #{{ configname }}: {{ default_value }}
              {%- endif -%}
              {%- endmacro -%}
              {%- from 'salt/formulas.jinja' import file_roots, formulas with context -%}    <======================
              ##### Primary configuration settings #####
              ##########################################
              # This configuration file is used to manage the behavior of the Salt Master
              # Values that are commented out but have no space after the comment are
              # defaults that need not be set in the config. If there is a space after the
              [...]
              ---
     Started: 04:18:21.410948
    Duration: 271.237 ms
     Changes:   
```

I cloned the formula manually and have it referenced in my file_roots.  Not sure if that would have an impact over bringing it in via gitfs_remotes, but I'm trying to avoid adding the gitfs dependencies.

**Comment by iggy** [comment]
Can you paste the relevant bits of the master config and maybe the output of `find /wherever/you/checked/out/the/formula`

**Comment by mattwillsher** [comment]
The follow Saltfile entry works around the problem.

```yaml
salt-ssh:
  extra_filerefs:
    - salt://salt/formulas.jinja
```

#9878 cover the reason for extra_filerefs and notes that its possible it won't be needed one day.

The issue can be avoided if f_defaults.conf embedded the contents of formulas.jinja rather than including it.

**Comment by ryanfields** [comment]
Just dropping a note to confirm that the workaround provided by @mattwillsher also worked for me.

**Comment by iggy** [comment]
We can't shove formulas.jinja into f_defaults.conf (as it's actually imported in 3 different files). We could add a note to the README file that mentions the issue though.

**Comment by edgan** [comment]
I ran into this issue and fixed it in a different way that I think is more portable. It is a bit ugly though.

You act like you are going to write the map.jinja file, but then say create false and replace false, effectively creating a noop. The upside is that is another to create the necessary file reference. You have to do this per formula.

common/init.sls:
include:
    - common.map

common/map.sls:
common_map.jinja:
  file.managed:
    - name: /var/tmp/common_map.jinja
    - source: salt://common/map.jinja
    - replace: False
    - create: False

**Comment by aboe76** [comment]
see also #17
