### ISSUE TITLE
Salt Config fails with CommandExecutionError

### ISSUE THREAD

**Issue by chbiel** [saltstack-formulas/salt-formula#223]
Hi,
we use salt master-minion setup with version 2015.8.8.2.

Sometime I see following problem occure when salt-fomrula tries to manage minion.d

``` file_|-salt-minion_|-/etc/salt/minion.d_|-recurse:
        ----------
        __run_num__:
            4
        changes:
            ----------
        comment:
            An exception occurred in this state: Traceback (most recent call last):
              File "/usr/lib/python2.7/site-packages/salt/state.py", line 1626, in call
                **cdata['kwargs'])
              File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1492, in wrapper
                return f(*args, **kwargs)
              File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 2493, in recurse
                manage_file(dest, src)
              File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 2347, in manage_file
                __salt__['file.remove'](path)
              File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 3124, in remove
                'Could not remove {0!r}: {1}'.format(path, exc)
            CommandExecutionError: Could not remove u'/etc/salt/minion.d/.': [Errno 22] Invalid argument: '/etc/salt/minion.d/.'
        duration:
            123268.429
        name:
            /etc/salt/minion.d
        result:
            False
        start_time:
            09:00:07.346626
```

version info:

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

someone have an idea?

the minion.d diroctory is empty after that fail.
My fear is, that the minion failes in the timeframe where the config is not set. In that case we have to go on the server and set in manually, what is not how it should be.

It seem like it works when I run the state a second time after it failed. 
And this is not regular or reproducable. I happens sometime and mostly not...

**Comment by iggy** [comment]
Never seen anything like that. Do you have a reproducible test case?

**Comment by aboe76** [comment]
closing to old, and no updated information.
