### ISSUE TITLE
Data failed to compile on salt-minion 0.17.5

### ISSUE THREAD

**Issue by pinchal** [saltstack-formulas/salt-formula#254]
Hi!

I used to apply the salt.pkgrepo state in order to update my minions running on ubuntu 14.04. The current salt-minion version used in this distribution is the  v0.17.5, for which the option 'merge' seems to be problematic (salt/map.jinja line 155).

 I removed this option in my fork and I don't see any problem with that, is this 'merge' realy necessary?

```
[CRITICAL] Rendering SLS "base:salt.pkgrepo.debian" failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 77, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 169, in render_jinja_tmpl
    output = jinja_env.from_string(tmplstr).render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/salt/map.jinja", line 152, in top-level template code
    {% set salt_settings = salt['pillar.get'](
TypeError: get() got an unexpected keyword argument 'merge'

local:
    Data failed to compile:
----------
    Rendering SLS "base:salt.pkgrepo.debian" failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 77, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 169, in render_jinja_tmpl
    output = jinja_env.from_string(tmplstr).render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/salt/map.jinja", line 152, in top-level template code
    {% set salt_settings = salt['pillar.get'](
TypeError: get() got an unexpected keyword argument 'merge'
```

**Comment by gtmanfred** [comment]
0.17.5 is end of life many years ago, you will need to upgrade.
