### ISSUE TITLE
UnicodeDecodeError on Archlinux

### ISSUE THREAD

**Issue by alexander-bauer** [saltstack-formulas/salt-formula#311]
Hello all. I am trying to render the minion configuration on Archlinux, and seeing the following issue. This does not occur on my Ubuntu 16.10 master, and none of my configuration includes Unicode.

```
          ID: salt-minion
    Function: file.recurse
        Name: /etc/salt/minion.d
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 2823, in recurse
                  relname = sdecode(os.path.relpath(fn_, srcpath))
                File "/usr/lib/python2.7/posixpath.py", line 434, in relpath
                  i = len(commonprefix([start_list, path_list]))
                File "/usr/lib/python2.7/genericpath.py", line 79, in commonprefix
                  s1 = min(m)
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
     Started: 13:51:55.243570
    Duration: 748.211 ms
     Changes:   
```

Here is my versions report.
```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.25.1
         Python: 2.7.13 (default, Feb 11 2017, 12:22:40)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.1
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.10.13-1-ARCH
         system: Linux
        version: Not Installed
```

As one can see, there are a lot of [`UnicodeDecodeError` issues](https://github.com/saltstack/salt/search?q=UnicodeDecodeError&type=Issues&utf8=%E2%9C%93) on the Saltstack GitHub, but the one that strikes me as relevant here is saltstack/salt#32975. Can anyone provide guidance or a workaround?

**Comment by aboe76** [comment]
@alexander-bauer, I have two machines running with this formula. one is a master the other just a minion.
I didn't come across this issue....could you provide some more data like what's in the pillar of the minion (mind to redact some private stuff if needed)

**Comment by gtmanfred** [comment]
Do you have a locale setup on your archlinux box?

**Comment by aboe76** [comment]
closing issue, stale
