### ISSUE TITLE
salt.master does not work with salt-ssh

### ISSUE THREAD

**Issue by johnkeates** [saltstack-formulas/salt-formula#334]
Running:
`salt-ssh host.example.net state.apply salt.master`

Results in:

 ```
         ID: salt-master
    Function: file.recurse
        Name: /etc/salt/master.d
      Result: False
     Comment: #### /etc/salt/master.d/f_defaults.conf ####
              Unable to manage file: Jinja error: salt/formulas.jinja
              Traceback (most recent call last):
                File "/var/tmp/.root_5ec184_salt/py2/salt/utils/templates.py", line 410, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/var/tmp/.root_5ec184_salt/py2/jinja2/environment.py", line 1008, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/var/tmp/.root_5ec184_salt/py2/jinja2/environment.py", line 780, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 17, in top-level template code
                File "/var/tmp/.root_5ec184_salt/py2/salt/utils/jinja.py", line 145, in get_source
                  raise TemplateNotFound(template)
              TemplateNotFound: salt/formulas.jinja
              
              ; line 17
              
              ---
              [...]
              {{ configname }}: {{ cfg_salt[configname]|json }}
              {%- else -%}
              #{{ configname }}: {{ default_value|json }}
              {%- endif -%}
              {%- endmacro -%}
              {%- from "salt/formulas.jinja" import file_roots, formulas with context -%}    <======================
              ##### Primary configuration settings #####
              ##########################################
              # This configuration file is used to manage the behavior of the Salt Master.
              # Values that are commented out but have an empty line after the comment are
              # defaults that do not need to be set in the config. If there is no blank line
              [...]
              ---
     Started: 18:22:42.998310
    Duration: 297.709 ms
     Changes:  
```

Using: ` salt-ssh 2017.7.1 (Nitrogen) `

**Comment by johnkeates** [comment]
Two years ago, this was reported to salt: https://github.com/saltstack/salt/issues/21370

**Comment by aboe76** [comment]
no more info added closing
