### ISSUE TITLE
Error on EL7/Python 2.7.5

### ISSUE THREAD

**Issue by Poil** [saltstack-formulas/salt-formula#386]
Hi,

With this pillar

```
salt:
  minion_remove_config: False
  master_remove_config: False
  install_packages: True
  minion:
    master: salt.engsec
    mine_interval: 30
```

I have these errors

```
018-10-05 11:51:20,521 [salt.state       ][ERROR   ][21189] Unable to manage file: Jinja error: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 364, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 86, in top-level template code
TypeError: 'NoneType' object is not iterable

; line 86

---
[...]
Runas_Alias {{ name }} = {{ ",".join(runas) }}
{%- endfor %}

# User privilege specification
{%- for user,specs in users.items() %}
  {%- for spec in specs %}    <======================
{{ user }} {{ spec }}
  {%- endfor %}
{%- endfor %}

# Group privilege specification
[...]
---
2018-10-05 11:51:21,479 [salt.state       ][ERROR   ][21189] #### /etc/salt/minion.d/f_defaults.conf ####
Unable to manage file: Jinja syntax error: no test named 'list'; line 1228

---
[...]

#####   elasticsearch connection settings  #####
##########################################
elasticsearch:
{%- for name, value in cfg_minion['elasticsearch'].items() %}
{%- if value is list %}    <======================
  {{ name }}:
{%- for objvalue in value %}
    - {{ objvalue }}
{%- endfor %}
{%- else %}
[...]
---
```

Best regards

**Comment by Poil** [comment]
sorry, wrong salt version on this node (2015.5.10)
